EMSDcmntDir/EMS/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.DAL;
using EMS.Models;

namespace EMS.Controllers
{
    public class AdministratorController : Controller
    {
        private EmployeeManagementContext db = new EmployeeManagementContext();
        //to filter DB based on user
        public static string userID;

        //to pass username to the views throughout the life cycle of using the system as a user 
        public static string staticName;

        // GET: Administrator
        public ActionResult Index(String id)
        {
            userID = id;
            using (EmployeeManagementContext db = new EmployeeManagementContext())
            {
                List<Employee> employees = db.Employees.ToList();
                List<Shift> shifts = db.Shifts.ToList();

                var employeeRecord = from e in employees
                                     where e.username == userID
                                     select new Employee
                                     {
                                          id = e.id,
                                          firstName = e.firstName,
                                          lastName = e.lastName,
                                          phoneNo = e.phoneNo,
                                          homeAddress = e.homeAddress,
                                          email = e.email,
                                          dob = e.dob,
                                          jobTitle = e.jobTitle,
                                          privilege = e.privilege,
                                          password = e.password,
                                          username = e.username
                                     };
                
                if (employeeRecord == null)
                {
                    return HttpNotFound();
                }
                
                staticName = id;
                ViewBag.name = staticName;
                ViewBag.id = userID; 
                return View(employeeRecord);
            }
        }
        public ActionResult EditDetails()
        {
            using (EmployeeManagementContext db = new EmployeeManagementContext())
            {
                List<Employee> employees = db.Employees.ToList();

                var employeeRecord = from e in employees
                                     where e.username == userID
                                     select new Employee
                                     {
                                         phoneNo = e.phoneNo,
                                         homeAddress = e.homeAddress,
                                         email = e.email,
                                         username = e.username,
                                         password = e.password
                                     };
                if (employeeRecord == null)
                {
                    return HttpNotFound();
                }
                ViewBag.id = userID;
                ViewBag.name = staticName;
                return View(employeeRecord.First());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDetails([Bind(Include = "dob,phoneNo,homeAddress,username,password")] Employee employee)
        {
            employee.username = userID;
            int n = int.Parse(employee.phoneNo.ToString());
            employee.phoneNo = n;
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id = userID;
            ViewBag.name = staticName;
            return View(employee);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMSDcmntDir/EMS/Controllers/DayOffController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.DAL;
using EMS.Models;

namespace EMS.Controllers
{
    public class DayOffController : Controller
    {
        private EmployeeManagementContext db = new EmployeeManagementContext();
        public static string staticName;

        // GET: DayOff
        public ActionResult Index()
        {
            var dayOffs = db.DayOffs.Include(d => d.Employee);
            ViewBag.name = AdministratorController.staticName;
            return View(dayOffs.ToList());
        }

        // GET: DayOff/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DayOff dayOff = db.DayOffs.Find(id);
            if (dayOff == null)
            {
                return HttpNotFound();
            }
            ViewBag.name = AdministratorController.staticName;
            return View(dayOff);
        }

        // GET: DayOff/Create
        public ActionResult Create()
        {
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName");
            ViewBag.name = AdministratorController.staticName;
            return View();
        }

        // POST: DayOff/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,date,status,employeeId")] DayOff dayOff)
        {
            if (ModelState.IsValid)
            {
                db.DayOffs.Add(dayOff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", dayOff.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(dayOff);
        }

        // GET: DayOff/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DayOff dayOff = db.DayOffs.Find(id);
            if (dayOff == null)
            {
                return HttpNotFound();
            }
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", dayOff.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(dayOff);
        }

        // POST: DayOff/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,date,status,employeeId")] DayOff dayOff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dayOff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", dayOff.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(dayOff);
        }

        // GET: DayOff/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DayOff dayOff = db.DayOffs.Find(id);
            if (dayOff == null)
            {
                return HttpNotFound();
            }
            ViewBag.name = AdministratorController.staticName;
            return View(dayOff);
        }

        // POST: DayOff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DayOff dayOff = db.DayOffs.Find(id);
            db.DayOffs.Remove(dayOff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMSDcmntDir/EMS/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.DAL;
using EMS.Models;

namespace EMS.Controllers
{
    public class LeaveController : Controller
    {
        private EmployeeManagementContext db = new EmployeeManagementContext();

        // GET: Leave
        public ActionResult Index()
        {
            var leaves = db.Leaves.Include(l => l.Employee);
            ViewBag.name = AdministratorController.staticName;
            return View(leaves.ToList());
        }

        // GET: Leave/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leave leave = db.Leaves.Find(id);
            if (leave == null)
            {
                return HttpNotFound();
            }
            ViewBag.name = AdministratorController.staticName;
            return View(leave);
        }

        // GET: Leave/Create
        public ActionResult Create()
        {
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName");
            ViewBag.name = AdministratorController.staticName;
            return View();
        }

        // POST: Leave/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,startDate,endDate,status,employeeId")] Leave leave)
        {
            if (ModelState.IsValid)
            {
                db.Leaves.Add(leave);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", leave.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(leave);
        }

        // GET: Leave/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leave leave = db.Leaves.Find(id);
            if (leave == null)
            {
                return HttpNotFound();
            }
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", leave.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(leave);
        }

        // POST: Leave/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,startDate,endDate,status,employeeId")] Leave leave)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leave).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", leave.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(leave);
        }

        // GET: Leave/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leave leave = db.Leaves.Find(id);
            if (leave == null)
            {
                return HttpNotFound();
            }
            ViewBag.name = AdministratorController.staticName;
            return View(leave);
        }

        // POST: Leave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Leave leave = db.Leaves.Find(id);
            db.Leaves.Remove(leave);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMSDcmntDir/EMS/Controllers/ShiftController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.DAL;
using EMS.Models;

namespace EMS.Controllers
{
    public class ShiftController : Controller
    {
        private EmployeeManagementContext db = new EmployeeManagementContext();

        // GET: Shift
        public ActionResult Index()
        {
            var shifts = db.Shifts.Include(s => s.Employee);
            ViewBag.name = AdministratorController.staticName;
            return View(shifts.ToList());
        }

        // GET: Shift/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shift shift = db.Shifts.Find(id);
            if (shift == null)
            {
                return HttpNotFound();
            }
            ViewBag.name = AdministratorController.staticName;
            return View(shift);
        }

        // GET: Shift/Create
        public ActionResult Create()
        {
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName");
            ViewBag.name = AdministratorController.staticName;
            return View();
        }

        // POST: Shift/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,date,attendance,employeeId")] Shift shift)
        {
            if (ModelState.IsValid)
            {
                db.Shifts.Add(shift);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", shift.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(shift);
        }

        // GET: Shift/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shift shift = db.Shifts.Find(id);
            if (shift == null)
            {
                return HttpNotFound();
            }
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", shift.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(shift);
        }

        // POST: Shift/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,date,attendance,employeeId")] Shift shift)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shift).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.employeeId = new SelectList(db.Employees, "id", "firstName", shift.employeeId);
            ViewBag.name = AdministratorController.staticName;
            return View(shift);
        }

        // GET: Shift/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shift shift = db.Shifts.Find(id);
            if (shift == null)
            {
                return HttpNotFound();
            }
            ViewBag.name = AdministratorController.staticName;
            return View(shift);
        }

        // POST: Shift/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Shift shift = db.Shifts.Find(id);
            db.Shifts.Remove(shift);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMSDcmntDir/EMS/Views/Shared/Administrator_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.name @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administrator Profile", "Index", "Administrator", new { id = ViewBag.name.ToLower(), area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employee Manager", "Index", "EmployeeList")</li>
                    <li>@Html.ActionLink("Shift Manager", "Index", "Shift")</li>
                    <li>@Html.ActionLink("DayOff Manager", "Index", "DayOff")</li>
                    <li>@Html.ActionLink("Leave Manager", "Index", "Leave")</li>
                    <li>@Html.ActionLink("Sign Out", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <h3><span class="badge">@ViewBag.name </span> @ViewBag.Title</h3>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Employee Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EMSDcmntDir/EMS/Views/Shared/Employee_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.name @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Home", "Index", "Employee", new { id = ViewBag.name.ToLower(), area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Schedule", "Schedule", "Employee")</li>
                    <li>@Html.ActionLink("Request", "Request", "Employee")</li>
                    <li>@Html.ActionLink("Sign Out", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content jumbotron">
        <h3><span class="badge">@ViewBag.name </span> @ViewBag.Title</h3>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Employee Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EMSDcmntDir/EMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Employee Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Login Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Employee Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>